### ISSUE TITLE
DNSMadeEasy records not being updated 

### ISSUE THREAD

**Issue by ptoal** [libdns/dnsmadeeasy#6]
I've been trying to get DME to work with Caddy, both dyndns and for certificates.

I've been unable to get this to work at all, and have had to make several modifications to different pieces of code, to get anything working.  Below is a log of my journey

Caddy version: 2.8.4
Latest libdns-dnsmadeeasy, caddy-dynamic_dns, john-k/dnsmadeeasy from github.

Simple Caddyfile:
```
        dynamic_dns {
                provider dnsmadeeasy {
                        api_key <redacted>
                        secret_key <redacted>
                        api_endpoint https://api.dnsmadeeasy.com/V2.0/
                }
                domains {
                        example.ca. test
                }
                check_interval 600s
                versions ipv4
                ttl 600s
        }
```

Logs:
```
{"level":"info","ts":"2024-10-31T04:04:14Z","msg":"serving initial configuration"}
{"level":"debug","ts":"2024-10-31T04:04:15Z","logger":"dynamic_dns","msg":"found DNS record","type":"A","name":"aaa","zone":"example.ca.","value":"24.146.1.1"}
{"level":"debug","ts":"2024-10-31T04:04:15Z","logger":"dynamic_dns","msg":"found DNS record","type":"A","name":"bbbb","zone":"example.ca.","value":"24.146.1.1"}
... snip ...
{"level":"debug","ts":"2024-10-31T04:04:15Z","logger":"dynamic_dns","msg":"found DNS record","type":"A","name":"test","zone":"example.ca.","value":"192.168.1.1"}
{"level":"info","ts":"2024-10-31T04:04:15Z","logger":"dynamic_dns","msg":"domain not found in DNS","domain":"test.example.ca.","type":"AAAA"}
{"level":"debug","ts":"2024-10-31T04:04:15Z","logger":"dynamic_dns","msg":"looked up current IPs from DNS","lastIPs":{"test.example.ca.":{"A":["192.168.1.1"],"AAAA":[""]}}}
{"level":"debug","ts":"2024-10-31T04:04:15Z","logger":"dynamic_dns.ip_sources.simple_http","msg":"lookup","type":"IPv4","endpoint":"https://icanhazip.com","ip":"24.146.1.1"}
{"level":"info","ts":"2024-10-31T04:04:15Z","logger":"dynamic_dns","msg":"updating DNS record","zone":"example.ca.","type":"A","name":"test","value":"24.146.1.1","ttl":600}
{"level":"error","ts":"2024-10-31T04:04:15Z","logger":"dynamic_dns","msg":"failed setting DNS record(s) with new IP address(es)","zone":"example.ca.","error":"request returned http error code 404"}

```

When I dig into the REST calls, I can see that there's an empty body being passed into the update request:
```
~~~ REQUEST ~~~
POST  /V2.0/dns/managed/6802041/records/updateMulti  HTTP/1.1
HOST   : api.dnsmadeeasy.com
HEADERS:
	Accept: application/json
	Content-Type: application/json
	Cookie: JSESSIONID=<redacted>
	User-Agent: go-resty/2.13.1 (https://github.com/go-resty/resty)
	X-Dnsme-Apikey: <redacted>
	X-Dnsme-Hmac: <redacted>
	X-Dnsme-Requestdate: Wed, 30 Oct 2024 18:00:43 GMT
BODY   :
null
```

Which is causing a 404 error:
```
~~~ RESPONSE ~~~
STATUS       : 404 Not Found
PROTO        : HTTP/1.1
RECEIVED AT  : 2024-10-30T14:00:43.899348338-04:00
TIME DURATION: 178.40039ms
HEADERS      :
	Allow: OPTIONS,PUT
	Connection: keep-alive
<snip>
```

First off, according to the DME API docs, the call to the updateMulti endpoint is a PUT, not a POST:
https://api-docs.dnsmadeeasy.com/#7aaea503-9ae5-4367-bac4-d0313592d772

When I dig into the code, I am confused by what's happening here:

https://github.com/libdns/dnsmadeeasy/blob/019960bfa7a26d6791da0e1d394d0a1db252c8a8/provider.go#L119

It looks like the code is trying to compare the ID of the DME record with the ID of the record to be updated, but the record to be updated doesn't have an ID, because it was created from a DNS lookup (with dyndns, anyway).

To get this to work, I've had to make a number of changes to this project and https://github.com/john-k/dnsmadeeasy.    I will submit my changes as PR's once I've tidied things up a little.

**Comment by ptoal** [comment]
Created an issue and submitted PR to the related repo: https://github.com/John-K/dnsmadeeasy/issues/5
Related PR coming for this repo.

**Comment by coandco** [comment]
Thanks for the detailed writeup!  This looks good, and I'm happy to merge it.  Unfortunately, John-K seems to be MIA, so getting your fixes merged into the John-K/dnsmadeeasy repo might be a harder road.  If all else fails, once everything's tested I can switch libdns/dnsmadeeasy to point to your repo.

**Comment by ptoal** [comment]
I'm not sure my repo is going to be any better than john-k's.  After struggling with this and also not being able to get the DNS-01 challenge to work for cert generation, I decided to cut my losses and try other solution for my use-case. So I'm not likely to maintain my fork going forward, unfortunately.

**Comment by coandco** [comment]
Fair enough.  I know the feeling -- I also maintain libdns/dreamhost, and when I ran into issues there (Dreamhost sometimes doesn't start serving new records for an hour or two after they're created through the API, making DNS-01 obnoxious to do) I ended up deciding to just CNAME the `_acme-challenge.domain.com` record to a registrar that updated immediately (Cloudflare in my case).
